name: Generate Posts JSON

on:
  push:
    paths:
      - 'materials/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate posts.js
        run: python scripts/generate_posts.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-generate posts.js based on materials folder updates"
          file_pattern: "data/posts.js"
